<?php require __DIR__ . '/../app/bootstrap.php';
\Punto\headers();
?><!doctype html>
<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Punto — Il lavoro trova la sua forma</title><meta name="description" content="Dalla prima richiesta alla consegna approvata. Punto è il workspace per piccoli studi e professionisti: clienti, commesse e revisioni nello stesso posto."><meta name="theme-color" content="#153b33"><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/base.css"><link rel="stylesheet" href="assets/landing.css"><link rel="stylesheet" href="assets/cinematic.css"><script src="assets/vendor/gsap.min.js" defer></script><script src="assets/vendor/ScrollTrigger.min.js" defer></script><script src="assets/landing.js" defer></script><script type="module" src="assets/scene.js"></script></head>
<body><a class="skip" href="#main">Vai al contenuto</a><header class="site-header"><a class="brand dark" href="./" aria-label="Punto, home">punto<i></i></a><nav aria-label="Navigazione principale"><a href="#metodo">Il metodo</a><a href="#workspace">Il workspace</a><a href="#domande">Domande</a></nav><a class="btn small" href="app.php">Entra in Punto <span>↗</span></a></header>
<main id="main">
<section class="hero" aria-labelledby="hero-title">
  <div class="hero-copy">
    <p class="eyebrow"><span class="live-dot"></span> IL WORKSPACE PER CHI CREA.</p>
    <h1 id="hero-title">Il lavoro trova<br>la sua <em>forma.</em></h1>
    <p class="hero-intro">Dai spazio alle idee.<br>Al resto, dai un punto.</p>
    <p class="hero-detail">Clienti, progetti e approvazioni. Un filo continuo dalla prima richiesta all’ultimo sì.</p>
    <div class="hero-actions"><a class="btn" href="app.php">Esplora il workspace <span class="arrow">↗</span></a><a class="text-link" href="#metodo">Come funziona <span>↓</span></a></div>
    <div class="hero-note"><span class="mini-mark">fp.</span><p>Ideato e sviluppato da <strong>Flavio Petrone</strong><br>Un progetto indipendente. Un software da provare.</p></div>
  </div>
  <div class="hero-art">
    <div class="scene-caption"><span class="eyebrow">UN’IDEA PRENDE FORMA</span><button id="motion-toggle" class="icon-btn" aria-label="Metti in pausa le animazioni" aria-pressed="false">Ⅱ</button></div>
    <div id="scene" role="img" aria-label="Scultura 3D interattiva: tre portali in ceramica verde e lime si compongono seguendo le fasi del progetto">
      <div class="scene-fallback" aria-hidden="true"><div></div><div></div><div></div><span>Un punto.<br>Infinite possibilità.</span></div>
    </div>
    <div class="scene-tag" aria-hidden="true"><span class="tag-dot"></span><span id="scene-status">Un nuovo inizio.</span><span>↗</span></div>
    <div class="scene-bottom"><span class="scene-index" aria-hidden="true">01<span> / 04</span></span><p id="phase-caption" aria-live="polite">Un’idea entra. Il progetto prende forma.</p><span class="drag-hint">Esplora con il cursore ↗</span></div>
  </div>
  <div class="hero-journey">
    <div class="journey-label"><span class="eyebrow">IL TUO PROGETTO, IN QUATTRO MOSSE</span><span>Scegli un punto del percorso ↘</span></div>
    <div class="phases" aria-label="Esplora le fasi del progetto">
      <button class="active" data-phase="0" aria-pressed="true"><small>01</small><span>Una richiesta.<em>Si parte da un’idea.</em></span><b>↗</b></button>
      <button data-phase="1" aria-pressed="false"><small>02</small><span>Una direzione.<em>Il team entra in gioco.</em></span><b>↗</b></button>
      <button data-phase="2" aria-pressed="false"><small>03</small><span>Un confronto.<em>Ogni versione conta.</em></span><b>↗</b></button>
      <button data-phase="3" aria-pressed="false"><small>04</small><span>Un bel sì.<em>Si chiude il cerchio.</em></span><b>↗</b></button>
    </div>
  </div>
</section>
<div class="principles"><span>Pensato per piccoli team, con grandi idee.</span><div><span>Studi creativi</span><i>·</i><span>Consulenti</span><i>·</i><span>Freelance</span></div><a href="app.php">Un posto per tutto ↗</a></div>
<section class="method section" id="metodo"><div class="section-top"><p class="eyebrow">01 / UN FILO CONTINUO</p><p>Il progetto avanza.<br>Le informazioni lo seguono.</p></div><h2>Da «ci sarebbe un’idea»<br>a <em>«è proprio così».</em></h2><div class="method-grid"><article><span class="step-number">01</span><h3>Ascolta.</h3><p>Il cliente apre una richiesta, spiega cosa serve e indica la priorità. Il brief ha già un posto.</p><div class="mini-request"><span class="pill warm">Nuova richiesta</span><strong>Una nuova pagina eventi</strong><span>Giulia · Atelier Nove <b>↗</b></span></div></article><article><span class="step-number">02</span><h3>Dai una direzione.</h3><p>Trasforma la richiesta in commessa. Assegna attività, stabilisci una scadenza e registra il tempo.</p><div class="mini-flow"><span>Da fare</span><span>In corso <i>↗</i></span><span>In revisione</span></div></article><article><span class="step-number">03</span><h3>Chiudi il cerchio.</h3><p>Condividi la consegna. Il cliente approva o chiede modifiche. Ogni versione e decisione resta nello storico.</p><div class="mini-approved"><span>✓</span><div><strong>Consegna approvata</strong><small>Una decisione chiara. Per tutti.</small></div></div></article></div></section>
<section class="workspace-section section" id="workspace"><div class="section-top"><p class="eyebrow">02 / IL TUO SPAZIO OPERATIVO</p><span class="pill">Progettato attorno al lavoro</span></div><div class="workspace-heading"><h2>Tutto sotto controllo.<br><em>Senza fare rumore.</em></h2><p>Una panoramica leggibile, poi il dettaglio che serve. Nessun passaggio perso tra messaggi, file e fogli sparsi.</p></div><a class="workspace-preview" href="app.php" aria-label="Apri il gestionale Punto"><div class="preview-top"><span><i></i><i></i><i></i></span><small>punto / workspace</small><b>Apri la demo ↗</b></div><img src="assets/workspace-preview.png" alt="Schermata reale di Punto: panoramica delle commesse, attività e richieste" loading="lazy" width="1440" height="1000"><div class="preview-placeholder"><span class="brand">punto<i></i></span><h3>Il tuo prossimo progetto<br>parte da qui.</h3><span>Apri il workspace ↗</span></div></a><div class="workspace-foot"><span>Interfaccia del gestionale funzionante, con dati dimostrativi.</span><a class="text-link" href="app.php">Provalo da tre punti di vista ↗</a></div></section>
<section class="roles-section section"><div class="role-title"><p class="eyebrow">03 / OGNUNO AL POSTO GIUSTO</p><h2>Stesso progetto.<br>Il tuo <em>punto di vista.</em></h2><p>Le persone vedono quello che serve al loro ruolo. Il lavoro resta collegato.</p></div><div class="roles"><article><span class="role-icon">↗</span><div><h3>Chi guida lo studio</h3><p>Clienti, richieste, persone e commesse. Una visione completa, con tempi ed esportazione dei report.</p></div><span>01</span></article><article><span class="role-icon">⌘</span><div><h3>Chi porta avanti il lavoro</h3><p>Le commesse assegnate, le attività da seguire, il tempo da registrare e i file da consegnare.</p></div><span>02</span></article><article><span class="role-icon">✓</span><div><h3>Chi si affida a te</h3><p>Un’area cliente per inviare richieste, commentare e approvare. Senza entrare nelle commesse degli altri.</p></div><span>03</span></article></div></section>
<section class="faq-section section" id="domande"><div><p class="eyebrow">I PUNTI DA CHIARIRE</p><h2>Concretamente?</h2></div><div class="faq"><details><summary>È solo una presentazione grafica?<span>+</span></summary><p>No. Il workspace salva richieste, attività, commenti e consegne in un database relazionale. Puoi provare un percorso completo, con autorizzazioni diverse per amministratore, team e cliente.</p></details><details><summary>Per chi è pensato?<span>+</span></summary><p>Per un piccolo studio di servizi o un professionista che lavora su commesse: web, design, consulenza e comunicazione. Gestisce il lavoro e le approvazioni; non sostituisce la contabilità o un sistema di fatturazione.</p></details><details><summary>Come funziona questa demo?<span>+</span></summary><p>In locale puoi entrare nei tre ruoli con un clic. Persone e commesse sono esempi inventati. Le modifiche vengono salvate: puoi creare un’attività e verificarne l’approvazione passando al ruolo cliente. L’accesso rapido è disabilitato fuori dall’ambiente locale.</p></details><details><summary>Che cosa c’è dietro?<span>+</span></summary><p>PHP 8.4, database MySQL o SQLite per l’avvio rapido, JavaScript e un’API con permessi verificati sul server. La scena 3D originale è realizzata con Three.js: materiali, luci e movimenti vengono renderizzati nel browser. GSAP coordina le transizioni. Puoi sospendere le animazioni; il sito rispetta anche la preferenza di movimento ridotto. Asset e font sono serviti localmente.</p></details></div></section>
<section class="closing"><span class="eyebrow">IL PROSSIMO PASSO HA UN POSTO.</span><h2>Facciamo<br><em>il punto.</em><span>↗</span></h2><a class="btn light" href="app.php">Entra nel workspace <span class="arrow">↗</span></a><p>Apri. Esplora. Porta avanti un progetto.</p></section></main><footer><a class="brand dark" href="./">punto<i></i></a><p>Ideato e sviluppato da Flavio Petrone.<br>Progetto personale dimostrativo · 2026</p><a href="#main">Torna su ↑</a></footer></body></html>
